# Generated by Django 2.0.5 on 2018-06-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher_id',
        ),
    ]
