# Generated by Django 2.0.5 on 2018-06-01 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0002_student_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100, unique=True)),
                ('dependancies', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modules', to='student.Student')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modules', to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('number_of_modules', models.IntegerField()),
                ('number_of_users', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='teacher.Teacher')),
            ],
        ),
    ]
