# Generated by Django 2.0.5 on 2018-06-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_teacher_id'),
        ('project_modules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='module',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modules', to='project_modules.Project'),
        ),
        migrations.AddField(
            model_name='module',
            name='students',
            field=models.ManyToManyField(null=True, related_name='modules', to='student.Student'),
        ),
    ]
