# Generated by Django 2.0.5 on 2018-06-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20180602_1533'),
        ('student', '0003_remove_student_teacher_id'),
        ('project_modules', '0003_auto_20180601_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='teacher',
            new_name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='project',
        ),
        migrations.RemoveField(
            model_name='module',
            name='students',
        ),
        migrations.AddField(
            model_name='module',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modules', to='student.Student'),
        ),
        migrations.AddField(
            model_name='module',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modules', to='teacher.Teacher'),
        ),
    ]
