# Generated by Django 2.0.5 on 2018-06-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_modules', '0005_auto_20180602_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='dependancies',
        ),
        migrations.AddField(
            model_name='module',
            name='dependencies',
            field=models.ManyToManyField(to='project_modules.Module'),
        ),
    ]
