# Generated by Django 2.0.5 on 2018-06-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_modules', '0008_remove_project_number_of_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
